name: secrets-behavior-test

on:
  workflow_dispatch:

jobs:
  pull-in-secret:
    runs-on: ubuntu-latest
    env:
      super_secret: ${{ secrets.SuperSecret }}
    steps:
      - name: Call secret straight from Github
        run: echo $super_secret

  try-and-use-it:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: See if it is still accessible in this step
        run: echo $super_secret
